#include <iostream>
using namespace std;
main ()
{
cout<<"           *     *    *                            "<<endl;
cout<<"             *     *    *                           "<<endl;
cout<<"              *     *     *                          "<<endl;
cout<<"             *     *     *                    "<<endl;
cout<<"            *     *     *                        "<<endl;
cout<<"           *     *     *                     "<<endl;
cout<<"             *     *     *                    "<<endl;
cout<<"******************************************  "<<endl;
cout<<" *                                      *      "<<endl;
cout<<"   *                                  *        "<<endl;
cout<<"     *                              *               "<<endl;
cout<<"       *                         *              "<<endl;
cout<<"         **********************               "<<endl;
cout<<"     #WELCOME TP F()():)Y APPLICATION#          "<<endl;
}